# Generated by Django 4.2.2 on 2023-09-04 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20200524_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\grivi\\Desktop\\Art_Gallery_Management_System_Django\\src\\media'),
        ),
        migrations.AlterField(
            model_name='mycart',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 12, 55, 34, 597971)),
        ),
        migrations.AlterField(
            model_name='myorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 4, 12, 55, 34, 597971)),
        ),
    ]
